### ISSUE TITLE
file is overwritten in temp path

### ISSUE THREAD

**Issue by kapilrc** [jeduan/cordova-plugin-crop#11]
After we crop the image, it is stored in tmp path but older image is replaced. So if we want to cancel the event after cropping, we cannot pull image from storage since it gives new replaced file

on line 30 can you change it to 
this.outputUri = Uri.fromFile(new File(getTempDirectoryPath() + "/" + System.currentTimeMillis()+ "-cropped.jpg"));

so that every image will be new.

Thanks in advance.

**Comment by jeduan** [comment]
Send a PR with this and I'll merge

**Comment by ghost** [comment]
@jeduan there ya go
