### ISSUE TITLE
Auto crop....

### ISSUE THREAD

**Issue by edvenkat** [jeduan/cordova-plugin-crop#18]
Hai friends......
We take the photo (with A4 Sheet and some background) using camera.......  We need to crop the A4 Sheet only (Without background) is possible...? please advice........

**Comment by jeduan** [comment]
https://github.com/jeduan/cordova-plugin-crop/issues/7#issuecomment-182879211

**Comment by edvenkat** [comment]
hai jeduan.....
Is possible to find A4 sheet area programmatically without user selecting......

**Comment by jeduan** [comment]
Your best bet is to find libraries for iOS and Android that do that and then build a Cordova plugin. I don't know any libraries that do that currently
