### ISSUE TITLE
code explaination

### ISSUE THREAD

**Issue by edvenkat** [jeduan/cordova-plugin-crop#23]
Hai jeduan
I need to show the one view controller.......... like  image and crop option inside the popup u displayed in this plugin....how to do this? I analysis the ur code i thinks following line..

UINavigationController *navigationController = [[UINavigationController alloc] initWithRootViewController:cropController];
 if (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad) {
        navigationController.modalPresentationStyle = UIModalPresentationFormSheet;
 }
  [self.viewController presentViewController:navigationController animated:YES completion:NULL];

but i don't know how to link with self.vieController.....
Please help me ya.. and send the step to do this please advice...........

**Comment by edvenkat** [comment]
how to link with self.delegate not found 
how to use the following line
[self.delegate cropViewController:self didFinishCroppingImage:self.cropView.croppedImage]; 

Please advice......

**Comment by jeduan** [comment]
Sorry, didn't understand the question. feel free to reopen.
