### ISSUE TITLE
How can I convert into a blob file?

### ISSUE THREAD

**Issue by marticrespi** [jeduan/cordova-plugin-crop#34]
Hi, after this example code:

            console.log('Cropped Image Path!: ' + path);
            // Do whatever you want with new path such as read in a file
            // Here we resolve the path to finish, but normally you would now want to read in the file

How can I read this image and then convert to a blob file to can upload it?

Thanks!

**Comment by jeduan** [comment]
Memory is blurry but I used `cordova-plugin-file` or `cordova-plugin-file-transfer`. Closing as this is not a bug.
