### ISSUE TITLE
Video croping

### ISSUE THREAD

**Issue by dimitri320** [jeduan/cordova-plugin-crop#37]
Is it possible to crop video files with this plugin?

**Comment by jeduan** [comment]
Nope

**Comment by dimitri320** [comment]
@jeduan Thanks a lot for your prompt reply!
Can you advice, will it be hard to modify your plugin so that it also works with videos? Or is it very hard and not even though a try?
Thanks!!

**Comment by jeduan** [comment]
This plugin doesn't really do much, it's just a very small bridge to PECropController (iOS) or android-crop (Android). You should have some success if you find relevant libraries for what you want to do and write a bridge, it should be fun, too.

**Comment by dimitri320** [comment]
@jeduan I only wish I was a bit more experienced with coding, I've just started with Angular2 like a few months back. But I'll try to give it a stab! Please do let me know if you'll come across anything useful for me to build on top of! Thanks!!:)
