### ISSUE TITLE
Documentation For Ionic 1 with Angular 1

### ISSUE THREAD

**Issue by rajnandan1** [jeduan/cordova-plugin-crop#38]
Hi,

Please show an example to use it with ionic 1

**Comment by divyasreekandalam** [comment]
Hallo Rajnandan1,
pls find code for ionic1 with Angular1
 var options = {
        quality: 100
      }
      plugins.crop.promise(imageUrl)
        .then(function success(newPath) {
          console.log(newPath);
        })
        .catch(function fail(err) {
          console.log("Image can't crop" + err);
        })
