### ISSUE TITLE
Support for free cropping?

### ISSUE THREAD

**Issue by ivarreukers** [jeduan/cordova-plugin-crop#39]
Is there support for free cropping? What I mean by that is, let the user also extend the corners and create rectangles and stuff.

Is this on the agenda? Or is there some sort of function/configuration/fork to use?

**Comment by jeduan** [comment]
Not on the agenda. Your best bet is finding a native plugin and then figuring out the best way to bridge it to Cordova. This plugin is a good starting point.

You might want to check out if new versions or configs of the native plugins this project uses (they are stated in the README) support the feature you want. if so, just a few changes to the native code might be needed.

Best of luck!
