### ISSUE TITLE
Custom Styling

### ISSUE THREAD

**Issue by gabebres** [jeduan/cordova-plugin-crop#42]
Hi,

More of a query.

Is there any way to apply custom style to the crop page? e.g. I would like to change the Cancel and Done font color and even background image of crop page.

BR

**Comment by jeduan** [comment]
You could do anything you want if you modify the native part of the code. I think you have to set the tint color in the ViewController might do it but not sure. Here's the relevant lines https://github.com/jeduan/cordova-plugin-crop/blob/master/src/ios/CTCrop.m#L35

**Comment by TeodorKolev** [comment]
How to style buttons? Where buttons come form?

**Comment by yoyodono** [comment]
Hi there, Idk if this question is related with the topic. But, I just want to change the "Cancel" and "OK" label. Can you advise me how or where should I change that?

Thanks !

**Comment by RashmiChandran** [comment]
> You could do anything you want if you modify the native part of the code. I think you have to set the tint color in the ViewController might do it but not sure. Here's the relevant lines https://github.com/jeduan/cordova-plugin-crop/blob/master/src/ios/CTCrop.m#L35

Where can I change the button style in android ?
