### ISSUE TITLE
Access data from cropped image

### ISSUE THREAD

**Issue by chrisbenseler** [jeduan/cordova-plugin-crop#9]
When using the crop, with some code like:

plugins.crop
.promise(imageURI)
.then( function(cropped_path) {
   document.getElementById("myimg").src = cropped_path;
});

I can't do "anything" with the new path from the image. The adb console (Android) always returns:

I/chromium(28689): [INFO:CONSOLE(0)] "Not allowed to load local resource: file:///storage/emulated/0/Android/data/io.ionic.starter/cache/cropped.jpg?1456771434075", source: http://192.168.10.35:8100/ (0)

It seems the new Android doesn't allow to read anything from local storage, and so it's impossible to (example:) read the binary from the file. I know this is not something related to the plugin, but I got stuck with the implementation: how can I access the cropped image? Am I missing anything.

**Comment by jeduan** [comment]
I see your source is `http://192.168.10.35:8100`. That won't work. You need to use localhost as the source if you want to access `file://` urls due to the way HTTP sandboxing works.

**Comment by chrisbenseler** [comment]
@jeduan you are right, this was the problem. I was running the (ionic) app with a livereload server. Without the livereload, it started to work. Thanks!
